apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    hi: hoy
spec:
  replicas: 3
  selector:
    matchLabels:
      hi: hoy
  template:
    metadata:
      labels:
        hi: hoy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80