apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standard-retain
spec:
  storageClassName: standard-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
