apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate
  annotations:
    kubernetes.io/change-cause: ver2
spec:
  selector:
    matchLabels:
      app: recreate
  replicas: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recreate
        svc: example
    spec:
      containers:
        - name: hello-world
          image: ahmadrafiee/go-hello-world:2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
---
apiVersion: v1
kind: Service
metadata:
  name: recreate
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: recreate
