apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  clusterIP: None
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hello-world-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-world
  labels:
    app: hello-world-sts
  annotations:
    kubernetes.io/change-cause: ver2
spec:
  serviceName: hello-world
  selector:
    matchLabels:
      app: hello-world-sts
  replicas: 6
  template:
    metadata:
      labels:
        app: hello-world-sts
        svc: example
    spec:
      containers:
        - name: hello-world
          image: ahmadrafiee/go-hello-world:2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
