apiVersion: v1
kind: Pod
metadata:
  name: nodename
spec:
  containers:
    - name: hello
      image: ondrejsika/go-hello-world:2
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
  nodeName: minikube
