apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-foo
  namespace: foo
  labels:
    app: ping
spec:
  containers:
  - name: sample-pod-a-container
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 3600']
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-bar
  namespace: bar
  labels:
    app: ping
spec:
  containers:
  - name: sample-pod-b-container
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 3600']
