apiVersion: v1
kind: Pod
metadata:
  name: private-pod
  labels:
    svc: example
spec:
  imagePullSecrets:
    - name: private-registry-credentials
  containers:
    - name: hello
      image: hub.dockerme.ir/pseudo-private/hello-world:latest
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: private-registry-credentials
stringData:
  .dockerconfigjson: '{"auths": {"hub.dockerme.ir": {"auth": "cHNldWRvLXByaXZhdGUtdXNlcjphc2RmYXNkZg=="}}}'
