---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pvc
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: busybox
        command: ['sh', '-c', 'sleep 3600']
        name: test-pvc
        volumeMounts:
        - name: test-pvc
          mountPath: /opt/
      volumes:
      - name: test-pvc
        persistentVolumeClaim:
          claimName: test-pvc
