apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-scale-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: scale-pvc