apiVersion: v1
kind: Namespace
metadata:
  name: devel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devel-user
  namespace: devel
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devel-user-full-access
  namespace: devel
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devel-user-role-binding
  namespace: devel
subjects:
  - kind: ServiceAccount
    name: devel-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devel-user-full-access
