apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-jenkins
  namespace: ci-testbed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole-jenkins
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-jenkins
subjects:
- kind: ServiceAccount
  name: serviceaccount-jenkins
  namespace: ci-testbed
roleRef:
  kind: ClusterRole
  name: clusterrole-jenkins
  apiGroup: rbac.authorization.k8s.io
