apiVersion: v1
kind: Service
metadata:
  name: hello-world-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 7070
      protocol: TCP
      targetPort: 80
  selector:
    app: hello-world-deploy
