apiVersion: v1
kind: Service
metadata:
  name: hello-world-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      # nodePort is optional
      nodePort: 31001
  selector:
    app: hello-world-deploy
