apiVersion: v1
kind: Service
metadata:
  name: hello-world-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hello-world-deploy
